export enum PokemonActionTypes {
    FETCH_POKEMONS_REQUEST = "FETCH_POKEMONS_REQUEST",
    FETCH_MORE_POKEMONS_REQUEST = "FETCH_MORE_POKEMONS_REQUEST",
    FETCH_POKEMONS_SUCCESS = "FETCH_POST_SUCCESS",
    FETCH_POKEMONS_FAILURE = "FETCH_POST_FAILURE"
}
